import { configColorsTypes } from '@/lib/types';

export const configColors: configColorsTypes = {
  primary: {
    bgColor: {
      default: 'bg-primary',
      25: 'bg-primary-25',
      50: 'bg-primary-50',
      100: 'bg-primary-100',
    },
    textColor: {
      default: 'text-primary',
      25: 'text-primary-25',
      50: 'text-primary-50',
      100: 'text-primary-100',
    },
    button: 'bg-primary hover:bg-primary-100',
    bgLayout: 'after:bg-primary',
    bgChatBubble: '!bg-primary-25 dark:!bg-primary-100',
    borderTriangle: '!border-l-primary-25 dark:!border-l-primary-100',
    borderInput: 'border-b border-primary',
  },
  orange: {
    bgColor: {
      default: 'bg-orange',
      25: 'bg-orange-25',
      50: 'bg-orange-50',
      100: 'bg-orange-100',
    },
    textColor: {
      default: 'text-orange',
      25: 'text-orange-25',
      50: 'text-orange-50',
      100: 'text-orange-100',
    },
    button: 'bg-orange hover:bg-orange-100',
    bgLayout: 'after:bg-orange',
    bgChatBubble: '!bg-orange-25 dark:!bg-orange-100',
    borderTriangle: '!border-l-orange-25 dark:!border-l-orange-100',
    borderInput: 'border-b border-orange',
  },
  merigold: {
    bgColor: {
      default: 'bg-merigold',
      25: 'bg-merigold-25',
      50: 'bg-merigold-50',
      100: 'bg-merigold-100',
    },
    textColor: {
      default: 'text-merigold',
      25: 'text-merigold-25',
      50: 'text-merigold-50',
      100: 'text-merigold-100',
    },
    button: 'bg-merigold hover:bg-merigold-100',
    bgLayout: 'after:bg-merigold',
    bgChatBubble: '!bg-merigold-25 dark:!bg-merigold-100',
    borderTriangle: '!border-l-merigold-25 dark:!border-l-merigold-100',
    borderInput: 'border-b border-merigold',
  },
  yellow: {
    bgColor: {
      default: 'bg-yellow',
      25: 'bg-yellow-25',
      50: 'bg-yellow-50',
      100: 'bg-yellow-100',
    },
    textColor: {
      default: 'text-yellow',
      25: 'text-yellow-25',
      50: 'text-yellow-50',
      100: 'text-yellow-100',
    },
    button: 'bg-yellow hover:bg-yellow-100',
    bgLayout: 'after:bg-yellow',
    bgChatBubble: '!bg-yellow-25 dark:!bg-yellow-100',
    borderTriangle: '!border-l-yellow-25 dark:!border-l-yellow-100',
    borderInput: 'border-b border-yellow',
  },
  softblue: {
    bgColor: {
      default: 'bg-softblue',
      25: 'bg-softblue-25',
      50: 'bg-softblue-50',
      100: 'bg-softblue-100',
    },
    textColor: {
      default: 'text-softblue',
      25: 'text-softblue-25',
      50: 'text-softblue-50',
      100: 'text-softblue-100',
    },
    button: 'bg-softblue hover:bg-softblue-100',
    bgLayout: 'after:bg-softblue',
    bgChatBubble: '!bg-softblue-25 dark:!bg-softblue-100',
    borderTriangle: '!border-l-softblue-25 dark:!border-l-softblue-100',
    borderInput: 'border-b border-softblue',
  },
  blue: {
    bgColor: {
      default: 'bg-blue',
      25: 'bg-blue-25',
      50: 'bg-blue-50',
      100: 'bg-blue-100',
    },
    textColor: {
      default: 'text-blue',
      25: 'text-blue-25',
      50: 'text-blue-50',
      100: 'text-blue-100',
    },
    button: 'bg-blue hover:bg-blue-100',
    bgLayout: 'after:bg-blue',
    bgChatBubble: '!bg-blue-25 dark:!bg-blue-100',
    borderTriangle: '!border-l-blue-25 dark:!border-l-blue-100',
    borderInput: 'border-b border-blue',
  },
  red: {
    bgColor: {
      default: 'bg-red',
      25: 'bg-red-25',
      50: 'bg-red-50',
      100: 'bg-red-100',
    },
    textColor: {
      default: 'text-red',
      25: 'text-red-25',
      50: 'text-red-50',
      100: 'text-red-100',
    },
    button: 'bg-red hover:bg-red-100',
    bgLayout: 'after:bg-red',
    bgChatBubble: '!bg-red-25 dark:!bg-red-100',
    borderTriangle: '!border-l-red-25 dark:!border-l-red-100',
    borderInput: 'border-b border-red',
  },
  pink: {
    bgColor: {
      default: 'bg-pink',
      25: 'bg-pink-25',
      50: 'bg-pink-50',
      100: 'bg-pink-100',
    },
    textColor: {
      default: 'text-pink',
      25: 'text-pink-25',
      50: 'text-pink-50',
      100: 'text-pink-100',
    },
    button: 'bg-pink hover:bg-pink-100',
    bgLayout: 'after:bg-pink',
    bgChatBubble: '!bg-pink-25 dark:!bg-pink-100',
    borderTriangle: '!border-l-pink-25 dark:!border-l-pink-100',
    borderInput: 'border-b border-pink',
  },
  purple: {
    bgColor: {
      default: 'bg-purple',
      25: 'bg-purple-25',
      50: 'bg-purple-50',
      100: 'bg-purple-100',
    },
    textColor: {
      default: 'text-purple',
      25: 'text-purple-25',
      50: 'text-purple-50',
      100: 'text-purple-100',
    },
    button: 'bg-purple hover:bg-purple-100',
    bgLayout: 'after:bg-purple',
    bgChatBubble: '!bg-purple-25 dark:!bg-purple-100',
    borderTriangle: '!border-l-purple-25 dark:!border-l-purple-100',
    borderInput: 'border-b border-purple',
  },
  brown: {
    bgColor: {
      default: 'bg-brown',
      25: 'bg-brown-25',
      50: 'bg-brown-50',
      100: 'bg-brown-100',
    },
    textColor: {
      default: 'text-brown',
      25: 'text-brown-25',
      50: 'text-brown-50',
      100: 'text-brown-100',
    },
    button: 'bg-brown hover:bg-brown-100',
    bgLayout: 'after:bg-brown',
    bgChatBubble: '!bg-brown-25 dark:!bg-brown-100',
    borderTriangle: '!border-l-brown-25 dark:!border-l-brown-100',
    borderInput: 'border-b border-brown',
  },
};
